### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [MiniHero95/db-labs#2]
Хорошим тоном считается запись всех sql команд заглавными буквами, а все остальное малыми. Например, в задании 1 должно быть SELECT ... FROM.... 
Все файлы должны содержать комментарии.
Задание 3 и 4 - в задании нет facid, LIKE используется для текстовых полей
Задание 5 - условие "не превышающий", то есть <= , а не <
Задание 7 - лучше выводить не все данные, а только "объекты" (если просят только "объекты"). Это касается и следующих заданий тоже. Также рекомендуется вместо LIKE, OR использовать IN(....)
Задание 8 - не выполнено, нет столбца качественной стоимости со значениями "дорогой" и "дешевый".
Задание 9 - не работает, выбираются пользователи, зарегистрированные и ранее. Также не нужно выводить все данные пользователей, достаточно фамилии, имени и memid.
Задание 11 - как различить какой ряд в возвращаемом результате относится к member, а какой к facility?
Задание 12 - зачем limit 1 ?
Задание 13 - а если вчера еще один зарегистрировался? тогда дата уже не верная. Надо по-другому реализовать алгоритм.
Задание 14 - условия заданы не верно, мы не знаем цифр 5 и 80.

**Comment by MiniHero95** [comment]
Исправил

**Comment by lasbio** [comment]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. задание 8 - "AS" работает только в первом SELECT при объединении.
3.  задание 10 - неправильно, в задании нет требования сортировки, т.е. надо отобрать первых 10 членов клуба. А у вас отобраны первые 10 по алфавиту.
4. задание 11 - кроме членов, отобраны и гости.
5. задание 14 - в прицепа даст результат заданный заданием. Но, разве нельзя из одной и той же таблицы выбрать данные без UNION?  UNION == лишнее действие, значит большее время выполнения.

**Comment by MiniHero95** [comment]
Исправил

**Comment by lasbio** [comment]
10 - а если удалить memid 3,7,9,10 вернет ли Ваш скрипт 10 записей?
11 - второй AS

**Comment by MiniHero95** [comment]
11 исправил

**Comment by lasbio** [comment]
11 - по заданию должна быть 1 колонка.

**Comment by MiniHero95** [comment]
исправил
