### ISSUE TITLE
лаба 3

### ISSUE THREAD

**Issue by lasbio** [MiniHero95/db-labs#3]
1. Нет комментариев
2. задание 2 - для полей DATETIME, TIMESTAMP достаточно своих функций, нет смысла использовать  LIKE
3. задание 4 - неправильная сортировка.
4. задание 6 - неправильно. Во-первых, у Вас в WHERE условия ">30" применяются для всех. Например, если резервирование стоит для гостя 35, а члена 25, то эта запись не будет отобрана даже если она сделана гостем. Во-вторых, стоимость бронирования == {стоимость единичной (на 30 минут) аренды объекта (guestcost или membercost)} * {количество аренд в день (bookings.slots) . В третьих, использование LIKE для TIMESTAMP 
5. Задание 7 - не выполнено.

**Comment by lasbio** [comment]
Задание 5 - не верно, условия задачи не выполнены.  Вы отобрали все теннисные корты, а не 1 и 2.  Вместо 1 колонки ФИО - две колонки.
Задание 7 - не верно, условия задачи не выполнены.

**Comment by MiniHero95** [comment]
5-исправил

**Comment by MiniHero95** [comment]
7-исправил
